# Use root/example as user/password credentials
version: '3.1'

services:
  db:
      image: mysql:lts
      restart: always
      volumes:
        - db_data:/var/lib/mysql
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_ROOT_HOST: 'localhost'
        MYSQL_TCP_PORT: 3306
      ports:
        - "3306:3306"
      expose:
        - 3306
      
volumes:
  db_data: